export function copyToClipboard(text: string): Promise<void> {
  if (typeof navigator === "undefined") return Promise.resolve();

  return navigator.clipboard.writeText(text);
}

export function downloadJSON(data: unknown, filename: string) {
  if (typeof window === "undefined") return;

  const blob = new Blob([JSON.stringify(data, null, 2)], {
    type: "application/json",
  });

  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = filename;

  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);

  URL.revokeObjectURL(url);
}

export function formatShareText(payload: SharePayload): string {
  return `
📊 Fitness Progress Report

Coach: ${payload.coachName}
Sharing enabled: ${payload.sharingEnabled ? "Yes" : "No"}

--- Body Stats ---
${
  payload.latestBodyStats
    ? `Weight: ${payload.latestBodyStats.weightKg} kg
Body Fat: ${payload.latestBodyStats.bodyFatPercent}%`
    : "No data"
}

--- InBody ---
${
  payload.latestInBody
    ? `Weight: ${payload.latestInBody.weightKg} kg
Body Fat: ${payload.latestInBody.bodyFatPercent}%`
    : "No data"
}

--- Nutrition ---
${
  payload.latestNutritionSummary
    ? `Calories: ${payload.latestNutritionSummary.calorieTarget} kcal
Protein: ${payload.latestNutritionSummary.proteinTargetGrams} g
Fat: ${payload.latestNutritionSummary.fatTargetGrams} g
Carbs: ${payload.latestNutritionSummary.carbsTargetGrams} g`
    : "No data"
}

--- Workouts ---
Sessions included: ${payload.savedWorkouts.length}

Generated by Fitsler Pro App
  `.trim();
}

import { SharePayload } from "@shared/types/share";
import jsPDF from "jspdf";

// ── Palette ───────────────────────────────────────────────────────────────────
const INDIGO  = [99,  102, 241] as const;
const DARK    = [15,  23,  42]  as const;
const BODY    = [30,  41,  59]  as const;
const MUTED   = [100, 116, 139] as const;
const DIVIDER = [226, 232, 240] as const;
const WHITE   = [255, 255, 255] as const;

function rgb(doc: jsPDF, type: "fill" | "text" | "draw", c: readonly [number, number, number]) {
  if (type === "fill")  doc.setFillColor(c[0], c[1], c[2]);
  if (type === "text")  doc.setTextColor(c[0], c[1], c[2]);
  if (type === "draw")  doc.setDrawColor(c[0], c[1], c[2]);
}

export function downloadPDFReport(payload: SharePayload) {
  if (typeof window === "undefined") return;

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const PW = doc.internal.pageSize.getWidth();
  const PH = doc.internal.pageSize.getHeight();
  const L = 20;
  const R = PW - 20;
  const W = R - L;
  let y = 0;

  // ── Footer helper ──────────────────────────────────────────────────────────
  const reportDate = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  function drawFooter() {
    const total = (doc.internal as unknown as { getNumberOfPages(): number }).getNumberOfPages();
    for (let p = 1; p <= total; p++) {
      doc.setPage(p);
      rgb(doc, "fill", DIVIDER);
      doc.rect(L, PH - 14, W, 0.3, "F");
      rgb(doc, "text", MUTED);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.text(`Generated by Fitsler  ·  ${reportDate}`, L, PH - 8);
      doc.text(`${p} / ${total}`, R, PH - 8, { align: "right" });
    }
  }

  // ── Page-break guard ───────────────────────────────────────────────────────
  function need(space: number) {
    if (y + space > PH - 22) { doc.addPage(); y = 28; }
  }

  // ── Header bar ────────────────────────────────────────────────────────────
  rgb(doc, "fill", DARK);
  doc.rect(0, 0, PW, 22, "F");
  rgb(doc, "fill", INDIGO);
  doc.rect(0, 20, PW, 3, "F");

  rgb(doc, "text", WHITE);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("FITSLER", L, 14);

  rgb(doc, "text", [180, 185, 255]);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Fitness Progress Report", L + 42, 14);

  if (payload.coachName) {
    rgb(doc, "text", [180, 185, 255]);
    doc.setFontSize(9);
    doc.text(`For: ${payload.coachName}`, R, 14, { align: "right" });
  }

  y = 34;

  // ── Section heading helper ────────────────────────────────────────────────
  function sectionHeading(title: string) {
    need(14);
    rgb(doc, "text", INDIGO);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(title.toUpperCase(), L, y);
    rgb(doc, "fill", INDIGO);
    doc.rect(L, y + 2, W, 0.4, "F");
    y += 9;
  }

  // ── Stat block helper (label + value side-by-side) ─────────────────────────
  function statBlock(label: string, value: string, x: number, blockW: number) {
    rgb(doc, "text", MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(label.toUpperCase(), x, y);

    rgb(doc, "text", BODY);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text(value, x, y + 7);
  }

  // ── Placeholder text ──────────────────────────────────────────────────────
  function noData(msg: string) {
    rgb(doc, "text", MUTED);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(10);
    doc.text(msg, L, y);
    y += 7;
  }

  // ── Body Stats ────────────────────────────────────────────────────────────
  sectionHeading("Body Stats");
  if (payload.latestBodyStats) {
    const bs = payload.latestBodyStats;
    statBlock("Weight", `${bs.weightKg} kg`, L, W / 3);
    statBlock("Body Fat", `${bs.bodyFatPercent}%`, L + W / 3, W / 3);
    if (bs.muscleMassKg != null)
      statBlock("Muscle Mass", `${bs.muscleMassKg} kg`, L + (W / 3) * 2, W / 3);
    y += 18;
    if (bs.notes) {
      rgb(doc, "text", MUTED);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.text(`Notes: ${bs.notes}`, L, y);
      y += 6;
    }
  } else {
    noData("No body stats recorded yet.");
  }

  // ── InBody ────────────────────────────────────────────────────────────────
  need(30);
  y += 4;
  sectionHeading("InBody Scan");
  if (payload.latestInBody) {
    const ib = payload.latestInBody;
    statBlock("Weight", `${ib.weightKg} kg`, L, W / 4);
    statBlock("Body Fat", `${ib.bodyFatPercent}%`, L + W / 4, W / 4);
    if (ib.skeletalMuscleMassKg != null)
      statBlock("Skeletal Muscle", `${ib.skeletalMuscleMassKg} kg`, L + (W / 4) * 2, W / 4);
    if (ib.fatFreeMassKg != null)
      statBlock("Fat-Free Mass", `${ib.fatFreeMassKg} kg`, L + (W / 4) * 3, W / 4);
    y += 18;
  } else {
    noData("No InBody scan recorded yet.");
  }

  // ── Nutrition ─────────────────────────────────────────────────────────────
  need(40);
  y += 4;
  sectionHeading("Nutrition Targets");
  if (payload.latestNutritionSummary) {
    const n = payload.latestNutritionSummary;
    const colW = W / 4;
    statBlock("Calories", `${n.calorieTarget} kcal`, L, colW);
    statBlock("Protein", `${n.proteinTargetGrams} g`, L + colW, colW);
    statBlock("Fat", `${n.fatTargetGrams} g`, L + colW * 2, colW);
    statBlock("Carbs", `${n.carbsTargetGrams} g`, L + colW * 3, colW);
    y += 18;
    // Macro ratio bar
    const total = n.proteinCalories + n.fatCalories + n.carbCalories || 1;
    const pPct = n.proteinCalories / total;
    const fPct = n.fatCalories / total;
    const cPct = n.carbCalories / total;
    const barH = 4;
    rgb(doc, "fill", [99, 102, 241]);  doc.rect(L, y, W * pPct, barH, "F");
    rgb(doc, "fill", [251, 191, 36]);  doc.rect(L + W * pPct, y, W * fPct, barH, "F");
    rgb(doc, "fill", [52, 211, 153]);  doc.rect(L + W * (pPct + fPct), y, W * cPct, barH, "F");
    y += barH + 3;
    rgb(doc, "text", MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.text(`Protein ${Math.round(pPct * 100)}%`, L, y);
    doc.text(`Fat ${Math.round(fPct * 100)}%`, L + W * pPct + 2, y);
    doc.text(`Carbs ${Math.round(cPct * 100)}%`, L + W * (pPct + fPct) + 2, y);
    y += 7;
  } else {
    noData("No nutrition plan saved yet.");
  }

  // ── Workouts ──────────────────────────────────────────────────────────────
  need(30);
  y += 4;
  sectionHeading("Workout Sessions");
  if (payload.savedWorkouts.length === 0) {
    noData("No workouts logged yet.");
  } else {
    const sessions = payload.savedWorkouts.slice(0, 20);
    sessions.forEach((record, i) => {
      need(8);
      const s = record.session;
      const dateStr = new Date(s.performedAt).toLocaleDateString("en-US", {
        month: "short", day: "numeric", year: "numeric",
      });
      const exCount = s.exercises.length;
      const setCount = s.exercises.reduce((sum, ex) => sum + ex.sets.filter(st => st.completed).length, 0);
      const rowY = y;

      // alternating row background
      if (i % 2 === 0) {
        rgb(doc, "fill", [248, 250, 252]);
        doc.rect(L, rowY - 4, W, 7, "F");
      }

      rgb(doc, "text", BODY);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.text(s.templateName ?? "Workout", L + 2, rowY);

      rgb(doc, "text", MUTED);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.text(dateStr, R - 55, rowY);
      doc.text(`${exCount} exercises · ${setCount} sets`, R, rowY, { align: "right" });

      y += 7;
    });
    if (payload.savedWorkouts.length > 20) {
      rgb(doc, "text", MUTED);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(8.5);
      doc.text(`+ ${payload.savedWorkouts.length - 20} more sessions not shown`, L, y);
      y += 6;
    }
  }

  drawFooter();
  doc.save("fitsler-progress-report.pdf");
}