export function copyToClipboard(text: string): Promise<void> {
  if (typeof navigator === "undefined") return Promise.resolve();

  return navigator.clipboard.writeText(text);
}

export function downloadJSON(data: unknown, filename: string) {
  if (typeof window === "undefined") return;

  const blob = new Blob([JSON.stringify(data, null, 2)], {
    type: "application/json",
  });

  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = filename;

  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);

  URL.revokeObjectURL(url);
}

export function formatShareText(payload: SharePayload): string {
  return `
📊 Fitness Progress Report

Coach: ${payload.coachName}
Sharing enabled: ${payload.sharingEnabled ? "Yes" : "No"}

--- Body Stats ---
${
  payload.latestBodyStats
    ? `Weight: ${payload.latestBodyStats.weightKg} kg
Body Fat: ${payload.latestBodyStats.bodyFatPercent}%`
    : "No data"
}

--- InBody ---
${
  payload.latestInBody
    ? `Weight: ${payload.latestInBody.weightKg} kg
Body Fat: ${payload.latestInBody.bodyFatPercent}%`
    : "No data"
}

--- Nutrition ---
${
  payload.latestNutritionSummary
    ? `Calories: ${payload.latestNutritionSummary.calorieTarget} kcal
Protein: ${payload.latestNutritionSummary.proteinTargetGrams} g
Fat: ${payload.latestNutritionSummary.fatTargetGrams} g
Carbs: ${payload.latestNutritionSummary.carbsTargetGrams} g`
    : "No data"
}

--- Workouts ---
Sessions included: ${payload.savedWorkouts.length}

Generated by Fitsler Pro App
  `.trim();
}

import { SharePayload } from "@/types/share";
import jsPDF from "jspdf";

export function downloadPDFReport(payload: SharePayload) {
  if (typeof window === "undefined") return;

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const left = 20;
  const right = pageWidth - 20;
  const maxWidth = right - left;
  let y = 20;

  function addTitle(text: string) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text(text, left, y);
    y += 10;
  }

  function addSectionTitle(text: string) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(text, left, y);
    y += 7;
  }

  function addBody(text: string) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);

    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, left, y);
    y += lines.length * 6 + 2;
  }

  function ensurePageSpace(minSpace = 20) {
    const pageHeight = doc.internal.pageSize.getHeight();

    if (y > pageHeight - minSpace) {
      doc.addPage();
      y = 20;
    }
  }

  addTitle("Fitsler Fitness Report");

  addBody(`Coach: ${payload.coachName}`);
  addBody(`Sharing enabled: ${payload.sharingEnabled ? "Yes" : "No"}`);

  ensurePageSpace();
  addSectionTitle("Body Stats");
  addBody(
    payload.latestBodyStats
      ? `Weight: ${payload.latestBodyStats.weightKg} kg
Body Fat: ${payload.latestBodyStats.bodyFatPercent}%`
      : "No body stats available."
  );

  ensurePageSpace();
  addSectionTitle("InBody");
  addBody(
    payload.latestInBody
      ? `Weight: ${payload.latestInBody.weightKg} kg
Body Fat: ${payload.latestInBody.bodyFatPercent}%`
      : "No InBody entry available."
  );

  ensurePageSpace();
  addSectionTitle("Nutrition");
  addBody(
    payload.latestNutritionSummary
      ? `Calories: ${payload.latestNutritionSummary.calorieTarget} kcal
Protein: ${payload.latestNutritionSummary.proteinTargetGrams} g
Fat: ${payload.latestNutritionSummary.fatTargetGrams} g
Carbs: ${payload.latestNutritionSummary.carbsTargetGrams} g`
      : "No nutrition summary available."
  );

  ensurePageSpace();
  addSectionTitle("Workouts");
  addBody(`Sessions included: ${payload.savedWorkouts.length}`);

  doc.save("fitness-progress-report.pdf");
}